# Generated by Django 5.2.5 on 2025-09-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planitarium_service", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ("seat",)},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("show_session", "row", "seat"),
                name="unique_ticket_seat_row_ticket",
            ),
        ),
    ]
