# Generated by Django 5.2.5 on 2025-09-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "planitarium_service",
            "0003_alter_ticket_options_alter_ticket_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="astronomy/photo/"
            ),
        ),
    ]
